name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Docker repository to tag the image with
        repository: deploymentking
        tags: latest
        tag_with_sha: true
        push: true
